Update django.yml

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -25,8 +25,12 @@ jobs:
         python-version: ${{ matrix.python-version }}
     - name: Install Dependencies
       run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
+        if [ "$RUNNER_OS" == "Linux" ]; then
+          python -m pip install --upgrade pip
+          cat ${workspaceFolder}/requirements.txt | sed -e '/^\\s*#.*$/d' -e '/^\\s*$/d' | xargs -n 1 ${workspaceFolder}/env/bin/pip3 install; if [ $? -eq 123 ]; then echo 'Running on linux pyaudiowpatch cannot be installed, do not be alarmed by the error'; fi
+        elif ["$RUNNER_OS" == "Windows" ]; then
+          Foreach ($package in (Get-Content -Path ${workspaceFolder}/requirements.txt)) { ${workspaceFolder}/env/Scripts/pip.exe install $package }
+        fi
     - name: Run Tests
       run: |
         pytest 
